name: main
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Build & Publish Docker image
        run: |
          export TAG=${GITHUB_SHA:0:7}
          export REGISTRY_IMAGE="docker.pkg.github.com/$(echo $GITHUB_REPOSITORY | awk '{print tolower($0)}')/web"
          echo $GITHUB_EVENT_PATH
          echo "$DOCKER_PASSWORD" | docker login docker.pkg.github.com -u "$DOCKER_USERNAME" --password-stdin
          docker build -t $REGISTRY_IMAGE:$TAG .
          docker push $REGISTRY_IMAGE:$TAG
        if: github.ref == 'refs/heads/master'
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v1

      - name: Update deployment config
        run: |
          export __REGISTRY_VERSION__=${GITHUB_SHA:0:7}
          export REGISTRY_IMAGE="docker.pkg.github.com/$(echo $GITHUB_REPOSITORY | awk '{print tolower($0)}')/web"
          sed -i "s|__REGISTRY_IMAGE__|${REGISTRY_IMAGE}|" .kube/deployment.yaml
          sed -i "s|__APP_NAME__|${__APP_NAME__}|" .kube/deployment.yaml
          sed -i "s|__ENVIRONMENT__|${__ENVIRONMENT__}|" .kube/deployment.yaml
          sed -i "s|__HOST__|${__HOST__}|" .kube/deployment.yaml
          sed -i "s|__NAMESPACE__|${__NAMESPACE__}|" .kube/deployment.yaml
          sed -i "s|__REGISTRY_VERSION__|${__REGISTRY_VERSION__}|" .kube/deployment.yaml

          cat .kube/deployment.yaml
        if: github.ref == 'refs/heads/master'
        env:
          __APP_NAME__: web
          __ENVIRONMENT__: dev
          __NAMESPACE__: ${{ secrets.K8S_NAMESPACE }}
          __HOST__: ${{ secrets.K8S_HOST }}

      - name: Deploy
        uses: actions-hub/kubectl@master
        if: github.ref == 'refs/heads/master'
        env:
          KUBE_CONFIG: ${{ secrets.K8S_KUBECONFIG }}
        with:
          args: apply -f .kube/deployment.yaml
